#-autodoc
#-autodoc        name: hello world sunset
#-autodoc description: Test automation using sun and persistant notify
#-autodoc        file: helloworld.yaml
#-autodoc

- alias: 'hello world sunset'
  trigger:
    platform: sun
    # Possible values: sunset, sunrise
    event: sunrise
    # Optional time offset. +/-HH:MM:SS
    # offset: '+00:03:00'
  action:
    service: persistent_notification.create
    data:
      message: "this is hello world sunset -message"
      title: "this is hello world sunset - title"
