
#----     Night time bedroom ceiling fan coordinated with Air conditioning
#
#--    turn fan on when air turned off  -
#
#-autodoc
#-autodoc        name: BR Fan ON when air off
#-autodoc description: When House goes is in night mode and the HVAC is cooling turn on the bedroom ceiling fan when the HVAC fan stops. (The HVAC Fan dance)
#-autodoc        file: hvac-ceiling-fan.yaml
#-autodoc
- alias: 'BR Fan ON when air off'
  trigger:
    platform: state
    entity_id: binary_sensor.arizona_thermostat_arizona_fan
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.night_mode
        state: 'on'
      - condition: state
        entity_id: sensor.arizona_thermostat_arizona_operation_mode
        state: 'cool'
  action:
    - service: switch.turn_on
      entity_id:
      - switch.br_ceiling_fan
      
#--    turn fan off when air turned on
#-
#-autodoc
#-autodoc        name: BR Fan OFF when air on
#-autodoc description: When House goes is in night mode  and the HVAC is cooling turn off the bedroom ceiling fan when the HVAC fan starts. (The HVAC Fan dance)
#-autodoc        file: hvac-ceiling-fan.yaml
#-autodoc
- alias: 'BR Fan OFF when air on'
  trigger:
    platform: state
    entity_id: binary_sensor.arizona_thermostat_arizona_fan
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.night_mode
        state: 'on'
      - condition: state
        entity_id: sensor.arizona_thermostat_arizona_operation_mode
        state: 'cool'
  action:
    - service: switch.turn_off
      entity_id:
      - switch.br_ceiling_fan

# turn off fan air automations when we get up
#-autodoc
#-autodoc        name: Stop the HVAC fan dance
#-autodoc description: When House goes into day mode turn of the HVAC fan dance automation.
#-autodoc        file: hvac-ceiling-fan.yaml
#-autodoc
- alias: 'Stop the HVAC fan dance'
  initial_state: False
  trigger:
    platform: state
    entity_id: input_boolean.night_mode
    from: 'on'
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.br_ceiling_fan
    - service: homeassistant.turn_off
      entity_id: group.hvac_automations_g

      

#-autodoc
#-autodoc        name: zzz enable the HVAC fan dance
#-autodoc description: When House goes into night mode turn on the HVAC fan dance automation.
#-autodoc        file: hvac-ceiling-fan.yaml
#-autodoc

- alias: 'zzz enable the HVAC fan dance'
  trigger:
    platform: state
    entity_id: input_boolean.night_mode
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: group.hvac_automations_g

#-autodoc
#-autodoc        name: zzz enable the HVAC fan dance
#-autodoc description: When House goes into night mode, HVAC is in cool mode, and HVAC fan is off turn on the bedroom ceiling fan.
#-autodoc        file: hvac-ceiling-fan.yaml
#-autodoc
- alias: 'start ceiling fan if hvac not running night'
  trigger:
    platform: state
    entity_id: input_boolean.night_mode
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.arizona_thermostat_arizona_fan
        state: 'off'
      - condition: state
        entity_id: sensor.arizona_thermostat_arizona_operation_mode
        state: 'cool'
  action:
    - service: switch.turn_on
      entity_id: switch.br_ceiling_fan
      
      
