# the overhead light switch  and hall switch will always turn night mode off
#-autodoc
#-autodoc        name: switch off night mode br oh trigger
#-autodoc description: When the bedroom over head or hall light is turned on change from night to day.  This automation is enable 30 minutes after House enters night mode.
#-autodoc              This automation is enabled 30 minutes after House enters night mode and disables itself when run.
#-autodoc        file: night-day-mode.yaml
#-autodoc
- alias: 'switch off night mode br oh trigger'
  initial_state: False
  trigger:
    - platform: state
      entity_id: switch.br_overhead
      # entity_id: group.br_mode_triggers
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.br_hall
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.night_mode
    state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.night_mode
    - service: homeassistant.turn_off
      entity_id: automation.switch_off_night_mode_br_oh_trigger
      
      
      
- alias: 'Day Mode WC motion off'
  trigger:
    platform: state
    entity_id: input_boolean.night_mode
    from: 'on'
    to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: automation.wc_light_on_with_motion